#!/usr/bin/env python3
"""Builds the Spanish versions of the hand-written pages (docs/es/...) from the English originals by exact
string replacement of visible copy. Run after editing the English pages: python site/i18n_es.py
Generated pages (catalogue, screen-time, subscriptions, guides, embed) are produced in Spanish by site/build.py.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
SITE = "https://furiadelimon.github.io/worth-one"

COMMON = [
    ('<html lang="en">', '<html lang="es">'),
    ('<a href="drops/">Explore</a><a href="about.html">About</a><a href="es/" hreflang="es">Español</a>', '<a href="drops/">Explorar</a><a href="about.html">Acerca de</a><a href="../" hreflang="en">English</a>'),
    ('<a href="drops/">Explore</a><a href="#faq">FAQ</a><a href="es/about.html" hreflang="es">Español</a>', '<a href="drops/">Explorar</a><a href="#faq">Preguntas</a><a href="../about.html" hreflang="en">English</a>'),
    ('<a href="../">Explore</a><a href="../../about.html">About</a><a href="../../es/drops/doomscroll-receipt/" hreflang="es">Español</a>', '<a href="../">Explorar</a><a href="../../about.html">Acerca de</a><a href="../../../drops/doomscroll-receipt/" hreflang="en">English</a>'),
    ('<a href="../">Explore</a><a href="../../about.html">About</a><a href="../../es/drops/subscription-receipt/" hreflang="es">Español</a>', '<a href="../">Explorar</a><a href="../../about.html">Acerca de</a><a href="../../../drops/subscription-receipt/" hreflang="en">English</a>'),
    ('<a href="drops/">Drops</a><a href="about.html">About</a></span>', '<a href="drops/">Explorar</a><a href="about.html">Acerca de</a><a href="../privacy.html" hreflang="en">English</a></span>'),
    ('Made by one person. Free things for strangers.', 'Hecho por una sola persona. Cosas gratis para desconocidos.'),
    ('<a href="drops/">Explore</a><a href="about.html">About</a><a href="notes/">Notes</a><a href="embed/">Embed a tool</a><a href="press/">Press kit</a><a href="privacy.html">Privacy</a>', '<a href="drops/">Explorar</a><a href="about.html">Acerca de</a><a href="embed/">Insertar</a><a href="privacy.html">Privacidad</a>'),
    ('<a href="./">Home</a><a href="drops/">Explore</a><a href="notes/">Notes</a><a href="privacy.html">Privacy</a>', '<a href="./">Inicio</a><a href="drops/">Explorar</a><a href="privacy.html">Privacidad</a>'),
    ('<a href="../../">Home</a><a href="../">Explore</a><a href="../../embed/">Embed this</a><a href="../../about.html">About</a><a href="../../privacy.html">Privacy</a>', '<a href="../../">Inicio</a><a href="../">Explorar</a><a href="../../embed/">Insertar</a><a href="../../about.html">Acerca de</a><a href="../../privacy.html">Privacidad</a>'),
    ('<a href="./">Home</a><a href="drops/">Drops</a><a href="about.html">About</a></footer>', '<a href="./">Inicio</a><a href="drops/">Explorar</a><a href="about.html">Acerca de</a></footer>'),
    ('<a href="https://github.com/Furiadelimon/worth-one">Source</a>', '<a href="https://github.com/Furiadelimon/worth-one">Código</a>'),
    ('Try another one', 'Prueba otra'),
    ('<span class="num">PLAY · DAILY</span><b>Words Before Coffee</b><p>Three words to wake up. Daily word games, no registration, no ads. In Spanish.</p>', '<span class="num">JUGAR · DIARIO</span><b>Words Before Coffee</b><p>Tres palabras para despertar. Juegos de palabras diarios, sin registro, sin anuncios.</p>'),
    ('<span class="num">PLAY · DAILY</span><b>Words Before Coffee</b><p>Daily word games, no registration, no ads. In Spanish.</p>', '<span class="num">JUGAR · DIARIO</span><b>Words Before Coffee</b><p>Juegos de palabras diarios, sin registro, sin anuncios.</p>'),
    ('The image is built on your phone. Nothing you type is uploaded.', 'La imagen se genera en tu móvil. Nada de lo que escribes se envía.'),
    ('The image is built on your device. Nothing you type is uploaded.', 'La imagen se genera en tu dispositivo. Nada de lo que escribes se envía.'),
    ('Send it to the friend who says they barely use their phone', 'Envíaselo al amigo que dice que casi no usa el móvil'),
    ('Send it to whoever shares your subscriptions', 'Envíaselo a quien comparta tus suscripciones'),
    ('<span class="num">#001 · TIME</span><span class="big">304 days</span><b>Doomscroll Receipt</b><p>What 2 hours a day of scrolling is over a decade.</p>', '<span class="num">#001 · TIEMPO</span><span class="big">304 días</span><b>Ticket de Doomscroll</b><p>Lo que son 2 horas de scroll al día en una década.</p>'),
    ('<span class="num">#002 · MONEY</span><span class="big">€1,799</span><b>Subscription Lifetime Receipt</b><p>What one €14.99 subscription costs over 10 years.</p>', '<span class="num">#002 · DINERO</span><span class="big">1.799 €</span><b>Ticket de Suscripciones</b><p>Lo que cuesta una suscripción de 14,99 € en 10 años.</p>'),
    ('<span class="num">REFERENCE</span><span class="big">1h→8h</span><b>Screen time, by the hour</b><p>What each amount adds up to over a decade.</p>', '<span class="num">REFERENCIA</span><span class="big">1h→8h</span><b>Tiempo de pantalla, hora a hora</b><p>Lo que suma cada cantidad en una década.</p>'),
    ('<span class="num">REFERENCE</span><span class="big">€1,680</span><b>Subscriptions, one by one</b><p>Netflix alone, Spotify alone, the gym alone: 10 years each.</p>', '<span class="num">REFERENCIA</span><span class="big">1.680 €</span><b>Suscripciones, una a una</b><p>Netflix sola, Spotify sola, el gimnasio solo: 10 años cada una.</p>'),
]

PAGES = {
    "index.html": [
        ('<title>Worth One? · Small things worth trying</title>', '<title>Worth One? · Cosas pequeñas que merecen un minuto</title>'),
        ('content="A small collection of free internet tools: your scrolling printed as a receipt, your subscriptions over ten years, daily word games. Free, no account, no ads. Made by one person."', 'content="Una pequeña colección de herramientas gratis: tu scroll impreso como un ticket, tus suscripciones a diez años, juegos de palabras diarios. Gratis, sin cuenta, sin anuncios. Hechas por una persona."'),
        ('content="Worth One? Small things worth trying."', 'content="Worth One? Cosas pequeñas que merecen un minuto."'), ('content="Free little tools for your time, your money and your curiosity. Some useful. Some strange. All quick."', 'content="Pequeñas herramientas gratis para tu tiempo, tu dinero y tu curiosidad. Algunas útiles. Algunas raras. Todas rápidas."'),
        ('assets/og.png"', 'assets/og-es.png"'),
        ('<span class="eyebrow">Free · no account · no ads</span>', '<span class="eyebrow">Gratis · sin cuenta · sin anuncios</span>'),
        ('<h1>Small things <em>worth trying.</em></h1>', '<h1>Cosas pequeñas <em>que merecen un minuto.</em></h1>'),
        ('<p class="lead">Little free tools for your time, your money and your curiosity. Some useful. Some strange. All quick.</p>', '<p class="lead">Pequeñas herramientas gratis para tu tiempo, tu dinero y tu curiosidad. Algunas útiles. Algunas raras. Todas rápidas.</p>'),
        ('Try one →</a><a class="btn ghost" href="drops/">Explore all</a>', 'Prueba una →</a><a class="btn ghost" href="drops/">Explorar todas</a>'),
        ('<div class="t">YOUR LIFE RECEIPT</div>', '<div class="t">TICKET DE TU VIDA</div>'),
        ('<div class="hl"><small>2 hours a day</small><b>= 304 days</b><em>of your next 10 years</em></div>', '<div class="hl"><small>2 horas al día</small><b>= 304 días</b><em>de tus próximos 10 años</em></div>'),
        ('<div class="ln"><span>Per year</span><b>30 days</b></div><div class="ln"><span>Next 20 years</span><b>1.7 years</b></div><div class="ln"><span>Your tier</span><b>Casual scroller</b></div>', '<div class="ln"><span>Al año</span><b>30 días</b></div><div class="ln"><span>Próximos 20 años</span><b>1,7 años</b></div><div class="ln"><span>Tu nivel</span><b>Scroll casual</b></div>'),
        ('<span class="kicker">#001 · time</span><h2>Doomscroll <em>Receipt</em></h2><p>Your scrolling, printed like a receipt. Ten seconds, one slider, one number you\'ll want to screenshot.</p><a class="btn" href="drops/doomscroll-receipt/" data-nav="DROP-001">Get your receipt →</a>', '<span class="kicker">#001 · tiempo</span><h2>Ticket de <em>Doomscroll</em></h2><p>Tu scroll, impreso como un ticket. Diez segundos, un control, un número del que querrás hacer captura.</p><a class="btn" href="drops/doomscroll-receipt/" data-nav="DROP-001">Saca tu ticket →</a>'),
        ('<div class="t">SUBSCRIPTION RECEIPT</div>', '<div class="t">TICKET DE SUSCRIPCIONES</div>'),
        ('<div class="hl"><small>€14.99 a month doesn\'t look like much</small><b>€1,799</b><em>over 10 years. That was one of them.</em></div>', '<div class="hl"><small>14,99 € al mes no parece mucho</small><b>1.799 €</b><em>en 10 años. Y eso era solo una.</em></div>'),
        ('<div class="ln"><span>Gym</span><b>€35.00</b></div><div class="ln tot" style="font-weight:700"><span>10 YEARS</span><b>€8,278</b></div>', '<div class="ln"><span>Gimnasio</span><b>€35.00</b></div><div class="ln tot" style="font-weight:700"><span>10 AÑOS</span><b>€8,278</b></div>'),
        ('<span class="kicker">#002 · money</span><h2>Subscription <em>Lifetime</em> Receipt</h2><p>Tap what you pay for. See what it costs over a decade. Untick one thing and watch the number drop.</p><a class="btn" href="drops/subscription-receipt/" data-nav="DROP-002">Print yours →</a>', '<span class="kicker">#002 · dinero</span><h2>Ticket de <em>Suscripciones</em></h2><p>Marca lo que pagas. Mira lo que cuesta en una década. Desmarca una cosa y observa cómo baja el número.</p><a class="btn" href="drops/subscription-receipt/" data-nav="DROP-002">Imprime el tuyo →</a>'),
        ('<h2>Explore by mood</h2>\n<p class="sub">A few now. More as they\'re made.</p>\n<div class="chips"><a class="chip" href="drops/#time">⏳ Time</a><a class="chip" href="drops/#money">💸 Money</a><a class="chip" href="drops/#brain">🧠 Brain</a><a class="chip" href="drops/#play">🎲 Play</a><a class="chip" href="drops/">All →</a></div>', '<h2>Explora por estado de ánimo</h2>\n<p class="sub">Unas pocas ahora. Más según se hacen.</p>\n<div class="chips"><a class="chip" href="drops/#time">⏳ Tiempo</a><a class="chip" href="drops/#money">💸 Dinero</a><a class="chip" href="drops/#brain">🧠 Cabeza</a><a class="chip" href="drops/#play">🎲 Juego</a><a class="chip" href="drops/">Todas →</a></div>'),
        ('<h2>From the same little corner of the internet</h2>', '<h2>Del mismo rincón de internet</h2>'),
        ('<span class="num">#003 · TIME</span><span class="tag soon">next</span><b>Weekends Left</b><p>A grid of the weekends you statistically have left. Poignant, not morbid.</p>', '<span class="num">#003 · TIEMPO</span><span class="tag soon">próximo</span><b>Fines de semana que te quedan</b><p>Una cuadrícula con los fines de semana que estadísticamente te quedan. Conmovedor, no morboso.</p>'),
        ('<h3>Why does this exist?</h3><p>There\'s no company behind this. One person makes these things and gives them away. At some point I wondered whether enough small useful things could eventually pay for something very real. So I\'m finding out. <a href="about.html">Why a car? →</a></p>', '<h3>¿Por qué existe esto?</h3><p>No hay ninguna empresa detrás. Una persona hace estas cosas y las regala. En algún momento me pregunté si suficientes cosas pequeñas y útiles podrían pagar algún día algo muy real. Así que lo estoy averiguando. <a href="about.html">¿Por qué un coche? →</a></p>'),
        ('<p class="small muted">Nothing is for sale and no payments are open. After you use a tool you can say whether it was worth €1. That\'s the whole experiment.</p>', '<p class="small muted">No se vende nada y no hay pagos abiertos. Después de usar una herramienta puedes decir si te valió 1 €. Ese es todo el experimento.</p>'),
        ('<span><b data-stat="users">0</b>people tried the tools</span><span><b data-stat="countries">0</b>countries</span><span><b data-stat="real">€0</b>contributions</span>', '<span><b data-stat="users">0</b>personas probaron las herramientas</span><span><b data-stat="countries">0</b>países</span><span><b data-stat="real">€0</b>aportaciones</span>'),
        ('<p class="small" style="margin-top:14px">If you want, I\'ll send the next one. No newsletter, just the drop.</p>', '<p class="small" style="margin-top:14px">Si quieres, te envío la siguiente. Sin newsletter, solo el drop.</p>'),
        ('placeholder="your@email" aria-label="email" required><button class="btn sm" type="submit">Send me the next drop</button>', 'placeholder="tu@email" aria-label="email" required><button class="btn sm" type="submit">Envíame el próximo drop</button>'),
    ],
    "about.html": [
        ('<title>About · Worth One?</title>', '<title>Acerca de · Worth One?</title>'),
        ('content="Who makes Worth One, why the tools are free, and what the car has to do with it. No company, no investors, one person."', 'content="Quién hace Worth One, por qué las herramientas son gratis y qué tiene que ver el coche. Sin empresa, sin inversores, una persona."'),
        ('content="About · Worth One?"', 'content="Acerca de · Worth One?"'), ('content="No company. No investors. One person making small things on the internet, and a car at the end of the experiment."', 'content="Sin empresa. Sin inversores. Una persona haciendo cosas pequeñas en internet, y un coche al final del experimento."'),
        ('<span class="eyebrow">About</span>\n<h1>No company. <em>One person.</em></h1>\n<p class="lead">I make small free things for the internet. Some useful, some strange, some just fun. This page is the long version, for anyone who wants it.</p>', '<span class="eyebrow">Acerca de</span>\n<h1>Sin empresa. <em>Una persona.</em></h1>\n<p class="lead">Hago cosas pequeñas y gratis para internet. Algunas útiles, algunas raras, algunas solo divertidas. Esta página es la versión larga, para quien la quiera.</p>'),
        ('<h2>What this is</h2>\n<p>A small collection of tools you can use in ten seconds without signing up for anything: a receipt for your scrolling, a receipt for your subscriptions, daily word games from the same kitchen, and whatever gets made next. They are free and they stay free. No ads, no account, nothing to install, nothing you type is uploaded.</p>', '<h2>Qué es esto</h2>\n<p>Una pequeña colección de herramientas que puedes usar en diez segundos sin registrarte en nada: un ticket de tu scroll, un ticket de tus suscripciones, juegos de palabras diarios de la misma cocina, y lo que se haga después. Son gratis y seguirán siéndolo. Sin anuncios, sin cuenta, sin instalar nada, sin subir nada de lo que escribes.</p>'),
        ('<h2>Why a car?</h2>\n<p>There are no investors and no master plan. At some point I wondered whether enough small useful things could eventually pay for something very real, and a used car was the most honest thing I could think of. So that is the experiment: make things, give them away, and after each one ask a single question. <i>Was this worth €1 to you?</i></p>', '<h2>¿Por qué un coche?</h2>\n<p>No hay inversores ni plan maestro. En algún momento me pregunté si suficientes cosas pequeñas y útiles podrían pagar algún día algo muy real, y un coche de segunda mano era lo más honesto que se me ocurrió. Ese es el experimento: hacer cosas, regalarlas y, después de cada una, hacer una sola pregunta. <i>¿Te ha valido 1 €?</i></p>'),
        ('<p>Right now that question only records an answer. No payments are open and nothing is charged. If enough people ever say yes, a normal payment provider will be connected and voluntary contributions will open, and the real total will be shown on the home page next to the answers. Target: €30,000. Real money received so far: €0.</p>', '<p>Ahora mismo esa pregunta solo registra una respuesta. No hay pagos abiertos y no se cobra nada. Si algún día suficiente gente dice que sí, se conectará un proveedor de pagos normal, se abrirán las aportaciones voluntarias y el total real se mostrará en la portada junto a las respuestas. Objetivo: 30.000 €. Dinero real recibido hasta ahora: 0 €.</p>'),
        ('<p>What it is not: not an investment, not a company, not charity, not crowdfunding for a product that comes later. The tools exist first. A contribution, if that day comes, is a small gift for something that already gave you something.</p>', '<p>Lo que no es: ni una inversión, ni una empresa, ni caridad, ni crowdfunding de un producto que llegará después. Las herramientas existen primero. Una aportación, si ese día llega, es un pequeño regalo por algo que ya te dio algo.</p>'),
        ('<h2>Who is behind it?</h2>\n<p>One person, deliberately not named. The tools should be judged on whether they are worth a minute of your time, not on who made them. Software does a lot of the routine work, under simple rules: no spam, no fake accounts, no bought attention, no fake numbers.</p>', '<h2>¿Quién está detrás?</h2>\n<p>Una persona, que deliberadamente no se nombra. Las herramientas deben juzgarse por si merecen un minuto de tu tiempo, no por quién las hizo. El software hace buena parte del trabajo rutinario, con reglas simples: sin spam, sin cuentas falsas, sin atención comprada, sin números falsos.</p>'),
        ('<h2>Why would I share one?</h2>\n<p>Because the results are personal and slightly ridiculous, which is exactly what people send each other. Every tool builds a share image on your device and gives you a link that lets a friend compare with you. Sharing is the only thing this project asks for.</p>\n<p>You can also <a href="embed/">put any tool on your own site</a> with one line of HTML, free.</p>', '<h2>¿Por qué compartiría una?</h2>\n<p>Porque los resultados son personales y un poco ridículos, que es justo lo que la gente se envía. Cada herramienta genera una imagen en tu dispositivo y te da un enlace para que alguien se compare contigo. Compartir es lo único que pide este proyecto.</p>\n<p>También puedes <a href="embed/">poner cualquier herramienta en tu propia web</a> con una línea de HTML, gratis.</p>'),
        ('<h2>FAQ</h2>', '<h2>Preguntas frecuentes</h2>'),
        ('<details><summary>Is anything charged when I click "Worth €1"?</summary><p>No. Nothing. The button records an answer only. Payments are closed until a human decides to open them, and the home page will say so clearly if that happens.</p></details>', '<details><summary>¿Se cobra algo al pulsar "Vale 1 €"?</summary><p>No. Nada. El botón solo registra una respuesta. Los pagos están cerrados hasta que una persona decida abrirlos, y la portada lo dirá claramente si ocurre.</p></details>'),
        ('<details><summary>Why a car and not something noble?</summary><p>Because it is true. A fake noble cause would be worse than an honest small one. You are never asked to care about the car; you are asked whether a free tool was worth €1.</p></details>', '<details><summary>¿Por qué un coche y no algo noble?</summary><p>Porque es verdad. Una causa noble fingida sería peor que una pequeña y honesta. Nunca se te pide que te importe el coche; se te pregunta si una herramienta gratis te valió 1 €.</p></details>'),
        ('<details><summary>Who are you?</summary><p>One person, not named. To reach the project, open an issue on <a href="https://github.com/Furiadelimon/worth-one">GitHub</a>.</p></details>', '<details><summary>¿Quién eres?</summary><p>Una persona, sin nombre. Para contactar con el proyecto, abre un issue en <a href="https://github.com/Furiadelimon/worth-one">GitHub</a>.</p></details>'),
        ('<details><summary>What happens to my data?</summary><p>Very little. An anonymous random id in your browser, the page you viewed, the country your connection comes from, and your answers. No names, no ads, no third-party trackers. If you leave an email, it is used for exactly what it says next to the box and nothing else. Details on the <a href="privacy.html">privacy page</a>.</p></details>', '<details><summary>¿Qué pasa con mis datos?</summary><p>Muy poco. Un identificador aleatorio anónimo en tu navegador, la página que has visto, el país de tu conexión y tus respuestas. Sin nombres, sin anuncios, sin rastreadores de terceros. Si dejas un email, se usa exactamente para lo que dice junto a la casilla y nada más. Detalles en la <a href="privacy.html">página de privacidad</a>.</p></details>'),
        ('<details><summary>What if the target is never reached?</summary><p>Then the tools were not worth it, and that is a valid result. Everything stays free anyway.</p></details>', '<details><summary>¿Y si nunca se alcanza el objetivo?</summary><p>Entonces las herramientas no valían la pena, y ese es un resultado válido. Todo sigue siendo gratis igualmente.</p></details>'),
        ('<details><summary>Can I suggest a tool, or embed one?</summary><p>Yes and yes. Suggest via <a href="https://github.com/Furiadelimon/worth-one/issues">GitHub issues</a>; embed via the <a href="embed/">embed page</a>.</p></details>', '<details><summary>¿Puedo proponer una herramienta o insertar una en mi web?</summary><p>Sí y sí. Propón en <a href="https://github.com/Furiadelimon/worth-one/issues">GitHub</a>; inserta desde la <a href="embed/">página de inserción</a>.</p></details>'),
        ('<details><summary>Terms, briefly</summary><p>The tools are provided as they are, for entertainment and general information, without warranties. Numbers are arithmetic on what you type, not professional advice of any kind. Contributions, if ever enabled, are voluntary gifts to a private person with no goods, services, rights or returns attached, and are not refundable except where the law requires it.</p></details>', '<details><summary>Condiciones, en breve</summary><p>Las herramientas se ofrecen tal cual, para entretenimiento e información general, sin garantías. Los números son aritmética sobre lo que escribes, no asesoramiento profesional. Las aportaciones, si algún día se habilitan, son regalos voluntarios a una persona privada sin bienes, servicios, derechos ni retornos asociados, y no son reembolsables salvo que la ley lo exija.</p></details>'),
        ('Try the first one →</a><a class="btn ghost sm" href="#" data-share="Small free internet tools worth a minute of your time:">Share this</a>', 'Prueba la primera →</a><a class="btn ghost sm" href="#" data-share="Pequeñas herramientas gratis que merecen un minuto:">Compartir</a>'),
    ],
    "privacy.html": [
        ('<title>Privacy · Worth One?</title>', '<title>Privacidad · Worth One?</title>'),
        ('<h1>Privacy</h1><p class="lead">Short, because there is not much to say.</p>', '<h1>Privacidad</h1><p class="lead">Corta, porque no hay mucho que decir.</p>'),
        ('<h3>What is collected</h3>\n<p>A random anonymous id stored in your browser (localStorage), the pages you view here, the country of your connection (derived from the network, not stored as an IP), the referrer or campaign tag that brought you here, and the answers you give (slider values, "worth €1" choices, shares).</p>', '<h3>Qué se recoge</h3>\n<p>Un identificador aleatorio anónimo guardado en tu navegador (localStorage), las páginas que ves aquí, el país de tu conexión (derivado de la red, no se guarda la IP), la referencia o etiqueta de campaña que te trajo, y las respuestas que das (valores de los controles, elecciones de "vale 1 €", compartidos).</p>'),
        ('<h3>What is not collected</h3>\n<p>No name, no account, no IP address stored, no fingerprinting, no third-party analytics, no advertising trackers, no cookies from other companies. Share images are rendered on your device and are not uploaded.</p>', '<h3>Qué no se recoge</h3>\n<p>Ni nombre, ni cuenta, ni dirección IP almacenada, ni huella digital, ni analítica de terceros, ni rastreadores publicitarios, ni cookies de otras empresas. Las imágenes para compartir se generan en tu dispositivo y no se suben.</p>'),
        ('<h3>Email</h3>\n<p>If you type an email to be told when supporting becomes possible, it is stored on a private server in the EU and used for that single purpose. Open an issue on the GitHub repository (or write to the project address once it is published) to have it deleted.</p>', '<h3>Email</h3>\n<p>Si escribes un email para que te avisen cuando sea posible apoyar, o para recibir el próximo drop, se guarda en un servidor privado en la UE y se usa solo para eso. Escribe a hello@wordsbeforecoffee.com para que se borre.</p>'),
        ('<h3>Where data lives</h3>\n<p>On a private server operated by the project owner (EU). Embedded widgets additionally count views by the embedding site\'s hostname, anonymously. Public pages are served by GitHub Pages, which has its own <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">privacy statement</a>. Events may pass through Cloudflare\'s network in transit.</p>', '<h3>Dónde están los datos</h3>\n<p>En un servidor privado operado por el responsable del proyecto (UE). Los widgets insertados cuentan además las vistas por el dominio de la web que los inserta, de forma anónima. Las páginas públicas las sirve GitHub Pages, que tiene su propia <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">política de privacidad</a>. Los eventos pueden pasar por la red de Cloudflare en tránsito.</p>'),
        ('<h3>Your rights</h3>\n<p>You can clear the anonymous id by clearing your browser storage. EU residents have the usual GDPR rights; contact via the repository. Controller: the individual behind this project, EU.</p>\n<p class="small muted">Last updated: September 2026.</p>', '<h3>Tus derechos</h3>\n<p>Puedes borrar el identificador anónimo vaciando el almacenamiento del navegador. Los residentes en la UE tienen los derechos habituales del RGPD; contacto a través del repositorio. Responsable: la persona detrás de este proyecto, UE.</p>\n<p class="small muted">Última actualización: septiembre de 2026.</p>'),
    ],
    "drops/doomscroll-receipt/index.html": [
        ('<title>Doomscroll Receipt · Screen time calculator: how much of your life goes to scrolling?</title>', '<title>Ticket de Doomscroll · Calculadora de tiempo de pantalla: ¿cuánta vida se te va en el scroll?</title>'),
        ('content="Free screen time calculator. Enter how long you scroll per day and get a receipt: per year, per decade, days of your life, and what a 30-minute cut gives back. No sign-up. Screenshot it, compare with a friend."', 'content="Calculadora gratis de tiempo de pantalla. Di cuánto haces scroll al día y recibe un ticket: al año, por década, días de tu vida y lo que recuperas quitando 30 minutos. Sin registro. Haz captura y compárala."'),
        ('content="Your phone\'s receipt: 2 hours a day = 304 days of the next decade"', 'content="El ticket de tu móvil: 2 horas al día = 304 días de la próxima década"'), ('content="Type how long you scroll. Get the receipt. Free, ten seconds, no account."', 'content="Di cuánto haces scroll. Recibe el ticket. Gratis, diez segundos, sin cuenta."'),
        ('assets/og-doomscroll.png"', 'assets/og-es-doomscroll.png"'),
        ('<span class="eyebrow">#001 · time · free</span>', '<span class="eyebrow">#001 · tiempo · gratis</span>'),
        ('Doomscroll <em>Receipt</em></h1>\n<p class="lead">How long do you scroll per day? Nobody\'s watching. Your phone knows: Settings → Screen Time (iPhone) or Digital Wellbeing (Android).</p>', 'Ticket de <em>Doomscroll</em></h1>\n<p class="lead">¿Cuánto tiempo haces scroll al día? Nadie mira. Tu móvil lo sabe: Ajustes → Tiempo de uso (iPhone) o Bienestar digital (Android).</p>'),
        ('<label for="h"><b>Scrolling per day:</b>', '<label for="h"><b>Scroll al día:</b>'),
        ('<h3>YOUR LIFE RECEIPT</h3>', '<h3>TICKET DE TU VIDA</h3>'), ('worth one? · doomscroll receipt · #', 'worth one? · ticket de doomscroll · #'),
        ('<div class="hl"><small id="hl_top">2h 30m a day</small><b id="hl_big">= 380 days</b><em>of your next 10 years</em></div>', '<div class="hl"><small id="hl_top">2h 30m al día</small><b id="hl_big">= 380 días</b><em>de tus próximos 10 años</em></div>'),
        ('<span>Scrolling / day</span>', '<span>Scroll / día</span>'), ('<span>Per week</span>', '<span>A la semana</span>'), ('<span>Per year</span>', '<span>Al año</span>'),
        ('<span>Next 5 years</span>', '<span>Próximos 5 años</span>'), ('<span>Next 10 years</span>', '<span>Próximos 10 años</span>'), ('<span>Next 20 years</span>', '<span>Próximos 20 años</span>'),
        ('<span>10 years of scrolling ≈</span>', '<span>10 años de scroll ≈</span>'), ('<span>Your tier</span>', '<span>Tu nivel</span>'), ('<span>vs world average*</span>', '<span>vs media mundial*</span>'), ('<span>vs other receipts</span>', '<span>vs otros tickets</span>'),
        ('<span>TOTAL, 10 YEARS</span>', '<span>TOTAL, 10 AÑOS</span>'), ('no refunds · but see below', 'sin devoluciones · pero mira abajo'),
        ('The refund department</h2>\n<p>Recover <b><span id="mLbl">30</span> min/day</b> and the receipt changes.</p>', 'Departamento de devoluciones</h2>\n<p>Recupera <b><span id="mLbl">30</span> min/día</b> y el ticket cambia.</p>'),
        ('<span>time reclaimed / year</span>', '<span>tiempo recuperado / año</span>'), ('<span>over 10 years</span>', '<span>en 10 años</span>'),
        ('That is not a lecture. It\'s arithmetic. Do with it what you want.', 'No es un sermón. Es aritmética. Haz con ella lo que quieras.'),
        ('<h2>What this screen time calculator actually does</h2>\n<p>It takes one number, the time you spend scrolling social feeds per day, and multiplies it out: per week, per year (in full 24-hour days), then over the next 5, 10 and 20 years. It then translates the 10-year figure into things people recognise (books, languages, TV series), gives you a tier name and shows how far you are from the world average. The "refund department" runs the same arithmetic on the minutes you decide to take back.</p>', '<h2>Qué hace realmente esta calculadora de tiempo de pantalla</h2>\n<p>Toma un número, el tiempo que pasas haciendo scroll al día, y lo multiplica: a la semana, al año (en días completos de 24 horas) y en los próximos 5, 10 y 20 años. Luego traduce la cifra de 10 años a cosas reconocibles (libros, idiomas, series), te da un nombre de nivel y muestra a qué distancia estás de la media mundial. El "departamento de devoluciones" hace la misma aritmética con los minutos que decidas recuperar.</p>'),
        ('<h3>How to get a real number</h3>\n<p>Open Screen Time (iPhone) or Digital Wellbeing (Android) and look at the weekly total for social and entertainment apps, then divide by seven. Most people underestimate by 30 to 50 percent, which is why the slider starts at 2h30, close to the global average. Curious how that compares by age? See <a href="../../screen-time/average-by-age/">average screen time by age</a>.</p>', '<h3>Cómo conseguir un número real</h3>\n<p>Abre Tiempo de uso (iPhone) o Bienestar digital (Android), mira el total semanal de apps sociales y de entretenimiento y divide entre siete. La mayoría se queda corta entre un 30 y un 50 por ciento, por eso el control empieza en 2h30, cerca de la media mundial. ¿Curiosidad por cómo cambia con la edad? Mira el <a href="../../screen-time/average-by-age/">tiempo de pantalla medio por edad</a>.</p>'),
        ('<h3>Why days instead of hours</h3>\n<p>"Two hours a day" sounds like a habit. "Thirty days a year" sounds like a decision. Same number. The receipt exists because the second framing is the one people remember, and the one they send to a friend.</p>', '<h3>Por qué días y no horas</h3>\n<p>"Dos horas al día" suena a hábito. "Treinta días al año" suena a decisión. Es el mismo número. El ticket existe porque la segunda forma es la que la gente recuerda, y la que envía a un amigo.</p>'),
        ('<h3>What it is not</h3>\n<p>It is not a diagnosis, not a health claim and not a judgement. Some scrolling is rest, some is work, some is joy. The receipt only shows the total so that whatever you decide, you decide it with the number in front of you.</p>', '<h3>Lo que no es</h3>\n<p>No es un diagnóstico, ni una afirmación sobre salud, ni un juicio. Parte del scroll es descanso, parte es trabajo, parte es alegría. El ticket solo muestra el total para que, decidas lo que decidas, lo hagas con el número delante.</p>'),
        ('*World average time on social media is roughly 2h20/day (DataReportal, Digital 2025). Everything here is arithmetic on the number you typed, not advice about your health.', '*La media mundial en redes sociales ronda las 2h20/día (DataReportal, Digital 2025). Todo esto es aritmética sobre el número que escribiste, no consejo sobre tu salud.'),
        ("[1,'Light thumb'],[2,'Casual scroller'],[3,'Regular'],[4,'Committed'],[6,'Heavy rotation'],[99,'Professional thumb athlete']", "[1,'Pulgar ligero'],[2,'Scroll casual'],[3,'Habitual'],[4,'Comprometido'],[6,'Alta rotación'],[99,'Atleta profesional del pulgar']"),
        ("'• reading '+books.toLocaleString('en')+' books (6h each)'", "'• leer '+books.toLocaleString('es')+' libros (6h cada uno)'"),
        ("'• learning '+(Math.floor(lang))+' language'+(lang>=2?'s':'')+' to conversational level'", "'• aprender '+(Math.floor(lang))+' idioma'+(lang>=2?'s':'')+' a nivel conversacional'"),
        ("'• watching every episode of Friends '+(friends<1?'0.'+Math.round(friends*10):Math.round(friends*10)/10)+' times'", "'• ver todos los episodios de Friends '+(friends<1?'0.'+Math.round(friends*10):Math.round(friends*10)/10)+' veces'"),
        ("'• the extended Lord of the Rings trilogy, '+lotr.toLocaleString('en')+' times'", "'• la trilogía extendida del Señor de los Anillos, '+lotr.toLocaleString('es')+' veces'"),
        ("const fmtD=d=>d<1?Math.round(d*24)+' hours':d<60?(Math.round(d*10)/10).toLocaleString('en')+' days':d<365?Math.round(d)+' days':(Math.round(d/365.25*100)/100).toLocaleString('en')+' years';", "const fmtD=d=>d<1?Math.round(d*24)+' horas':d<60?(Math.round(d*10)/10).toLocaleString('es')+' días':d<365?Math.round(d)+' días':(Math.round(d/365.25*100)/100).toLocaleString('es')+' años';"),
        ("$('#hl_top').textContent=fmtH(x)+' a day'", "$('#hl_top').textContent=fmtH(x)+' al día'"),
        ("$('#r_pct').textContent='more than '+c.pct_below+'% of '+c.n.toLocaleString('en')", "$('#r_pct').textContent='más que el '+c.pct_below+'% de '+c.n.toLocaleString('es')"),
        ("'<b>Someone sent you their receipt:</b> they scroll <b>'+fmtH(fv)+'/day</b> ('+fmtD(fv*365.25/24)+' a year). The slider is set to theirs. Move it to yours, then send it back.'", "'<b>Alguien te ha enviado su ticket:</b> hace scroll <b>'+fmtH(fv)+'/día</b> ('+fmtD(fv*365.25/24)+' al año). El control está en su valor. Ponlo en el tuyo y devuélveselo.'"),
        ("g.fillText('YOUR LIFE RECEIPT',540,180)", "g.fillText('TICKET DE TU VIDA',540,180)"), ("g.fillText('worth one? · doomscroll receipt',540,222)", "g.fillText('worth one? · ticket de doomscroll',540,222)"),
        ("g.fillText(fmtH(state.x)+' a day',540,330)", "g.fillText(fmtH(state.x)+' al día',540,330)"), ("g.fillText('of your next 10 years',540,505)", "g.fillText('de tus próximos 10 años',540,505)"),
        ("row('Per year',fmtD(state.yearD),620);row('Next 20 years',fmtD(state.d20),676);row('Your tier',state.tier,732);row('vs world average',(state.dif>=0?'+':'')+state.dif+'%',788)", "row('Al año',fmtD(state.yearD),620);row('Próximos 20 años',fmtD(state.d20),676);row('Tu nivel',state.tier,732);row('vs media mundial',(state.dif>=0?'+':'')+state.dif+'%',788)"),
        ("g.fillText('10 years of scrolling ≈',150,890)", "g.fillText('10 años de scroll ≈',150,890)"), ("row('TOTAL, 10 YEARS',fmtD(state.d10),1150,true)", "row('TOTAL, 10 AÑOS',fmtD(state.d10),1150,true)"),
        ("g.fillText('get yours · '+(window.WO_SITE||'').replace('https://','')+'/drops/doomscroll-receipt/',540,1225)", "g.fillText('el tuyo · '+(window.WO_SITE||'').replace('https://','')+'/es/drops/doomscroll-receipt/',540,1225)"),
        ("text:'My doomscroll receipt: '+fmtH(state.x)+'/day = '+fmtD(state.d10)+' over 10 years. What is yours? (free)'", "text:'Mi ticket de doomscroll: '+fmtH(state.x)+'/día = '+fmtD(state.d10)+' en 10 años. ¿Cuál es el tuyo? (gratis)'"),
        ("'my-doomscroll-receipt.png'", "'mi-ticket-doomscroll.png'"),
    ],
    "drops/subscription-receipt/index.html": [
        ('<title>Subscription Lifetime Receipt · Subscription cost calculator: what they really cost over 10 years</title>', '<title>Ticket de Suscripciones · Calculadora del coste de tus suscripciones en 10 años</title>'),
        ('content="Free subscription cost calculator. Tap your subscriptions, get a receipt: per month, per year, 10 years, 20 years, and what that money is in real things. No sign-up."', 'content="Calculadora gratis del coste de suscripciones. Marca las tuyas y recibe un ticket: al mes, al año, 10 años, 20 años, y qué es ese dinero en cosas reales. Sin registro."'),
        ('content="€14.99 a month doesn\'t look like much. 10 years: €1,799."', 'content="14,99 € al mes no parece mucho. 10 años: 1.799 €."'), ('content="Tap your subscriptions, get the receipt. Free, twenty seconds, no account."', 'content="Marca tus suscripciones, recibe el ticket. Gratis, veinte segundos, sin cuenta."'),
        ('assets/og-subscriptions.png"', 'assets/og-es-subscriptions.png"'),
        ('<span class="eyebrow">#002 · money · free</span>', '<span class="eyebrow">#002 · dinero · gratis</span>'),
        ('Subscription <em>Lifetime</em> Receipt</h1>\n<p class="lead">Tap what you pay for. Fix the prices if yours differ. The receipt prints what it costs over ten and twenty years.</p>', 'Ticket de <em>Suscripciones</em></h1>\n<p class="lead">Marca lo que pagas. Corrige los precios si los tuyos son otros. El ticket imprime lo que cuesta en diez y veinte años.</p>'),
        ('<b>Your subscriptions (per month)</b>', '<b>Tus suscripciones (al mes)</b>'), ('+ add your own', '+ añade la tuya'),
        ('<h3>SUBSCRIPTION RECEIPT</h3>', '<h3>TICKET DE SUSCRIPCIONES</h3>'), ('worth one? · lifetime edition · #', 'worth one? · edición vitalicia · #'),
        ('<div class="hl"><small id="hl_top">€0 a month doesn\'t look like much</small><b id="hl_big">€0</b><em>over 10 years</em></div>', '<div class="hl"><small id="hl_top">0 € al mes no parece mucho</small><b id="hl_big">€0</b><em>en 10 años</em></div>'),
        ('<span>Per month</span>', '<span>Al mes</span>'), ('<span>Per year</span>', '<span>Al año</span>'), ('<span>5 years</span>', '<span>5 años</span>'), ('<span>10 years</span>', '<span>10 años</span>'), ('<span>20 years</span>', '<span>20 años</span>'),
        ('<span>10 years buys ≈</span>', '<span>10 años compran ≈</span>'), ('<span>Your tier</span>', '<span>Tu nivel</span>'), ('<span>vs other receipts</span>', '<span>vs otros tickets</span>'), ('<span>TOTAL, 10 YEARS</span>', '<span>TOTAL, 10 AÑOS</span>'),
        ('auto-renews · like everything else', 'se renueva solo · como todo lo demás'),
        ('The cancel department</h2>\n<p>Untick one thing above and watch the 10-year line. That\'s the whole trick. No advice, just the number you were never shown.</p>\n<p class="small muted">Prices are typical 2026 list prices and only defaults; edit them. No inflation, no investing, no "if you had bought Bitcoin". Just what you pay. Want the full method? <a href="../../guides/subscription-audit/">Audit your subscriptions in 20 minutes</a>.</p>', 'Departamento de bajas</h2>\n<p>Desmarca una cosa arriba y mira la línea de 10 años. Ese es todo el truco. Sin consejos, solo el número que nunca te enseñaron.</p>\n<p class="small muted">Los precios son los de lista típicos de 2026 y solo valores por defecto; edítalos. Sin inflación, sin inversiones, sin "si hubieras comprado Bitcoin". Solo lo que pagas. ¿Quieres el método completo? <a href="../../guides/subscription-audit/">Audita tus suscripciones en 20 minutos</a>.</p>'),
        ('<h2>What this subscription cost calculator does</h2>\n<p>You tap the subscriptions you pay for, correct the prices, and it prints the monthly and yearly total, then the 5, 10 and 20-year cost. The 10-year line is converted into things people can picture: a share of a car, coffees, weeks of groceries, flights. There is no inflation adjustment and no investment fantasy; it is only what leaves your account at today\'s prices.</p>', '<h2>Qué hace esta calculadora de suscripciones</h2>\n<p>Marcas las suscripciones que pagas, corriges los precios, e imprime el total mensual y anual, y después el coste a 5, 10 y 20 años. La línea de 10 años se convierte en cosas que se pueden imaginar: parte de un coche, cafés, semanas de compra, vuelos. Sin ajuste por inflación ni fantasías de inversión; solo lo que sale de tu cuenta a precios de hoy.</p>'),
        ('<h3>Why the 10-year line matters</h3>\n<p>Subscriptions are priced to feel small per month. Nobody signs up for "€1,680 of streaming per decade", but that is what €14 a month is. Seeing the decade total next to the monthly price is usually enough to cancel one thing, which is the entire purpose of this page.</p>', '<h3>Por qué importa la línea de 10 años</h3>\n<p>Las suscripciones están pensadas para parecer pequeñas al mes. Nadie se apunta a "1.680 € de streaming por década", pero eso son 14 € al mes. Ver el total de la década junto al precio mensual suele bastar para dar de baja una cosa, que es el único propósito de esta página.</p>'),
        ('<h3>How to use it honestly</h3>\n<p>Include the ones you forget: cloud storage, an app you no longer open, the second streaming service, the phone insurance. Then remove one and watch the receipt reprint. Repeat until the number stops bothering you.</p>', '<h3>Cómo usarla con honestidad</h3>\n<p>Incluye las que olvidas: el almacenamiento en la nube, una app que ya no abres, el segundo servicio de streaming, el seguro del móvil. Luego quita una y mira cómo se reimprime el ticket. Repite hasta que el número deje de molestarte.</p>'),
        ('["Gym",35,1]', '["Gimnasio",35,1]'), ('["Dating app",20,0]', '["App de citas",20,0]'), ('["News / magazine",10,0]', '["Prensa / revista",10,0]'), ('["Meal kit",60,0]', '["Comida a domicilio",60,0]'), ('["Phone plan",20,0]', '["Tarifa móvil",20,0]'), ('["ChatGPT / AI",20,0]', '["ChatGPT / IA",20,0]'),
        ('const tiers=[[25,"Minimalist"],[60,"Streaming citizen"],[120,"Bundle enjoyer"],[200,"Recurring revenue hero"],[1e9,"The landlord\'s favourite tenant"]];', 'const tiers=[[25,"Minimalista"],[60,"Ciudadano del streaming"],[120,"Amante del pack"],[200,"Héroe del ingreso recurrente"],[1e9,"El inquilino favorito del casero"]];'),
        ('\'<div class="c">nothing selected</div>\'', '\'<div class="c">nada seleccionado</div>\''),
        ('$("#hl_top").textContent=cur+m.toFixed(2)+" a month doesn\'t look like much"', '$("#hl_top").textContent=cur+m.toFixed(2)+" al mes no parece mucho"'),
        ('const eq=[`• ${(y10/30000*100).toFixed(0)}% of the car this site wants (${cur}30,000)`,`• ${Math.round(y10/3).toLocaleString("en")} coffees at ${cur}3`,`• ${Math.round(y10/80).toLocaleString("en")} weeks of groceries at ${cur}80`,`• ${(y10/1200).toFixed(1)} return flights at ${cur}1,200`];', 'const eq=[`• ${(y10/30000*100).toFixed(0)}% del coche que quiere esta web (${cur}30.000)`,`• ${Math.round(y10/3).toLocaleString("es")} cafés a ${cur}3`,`• ${Math.round(y10/80).toLocaleString("es")} semanas de compra a ${cur}80`,`• ${(y10/1200).toFixed(1)} vuelos ida y vuelta a ${cur}1.200`];'),
        ('$(\'#r_pct\').textContent=\'more than \'+c.pct_below+\'% of \'+c.n.toLocaleString(\'en\')', '$(\'#r_pct\').textContent=\'más que el \'+c.pct_below+\'% de \'+c.n.toLocaleString(\'es\')'),
        ('const n=prompt("Name of the subscription?");if(!n)return;const p=+prompt("Price per month?","9.99")||0;', 'const n=prompt("¿Nombre de la suscripción?");if(!n)return;const p=+prompt("¿Precio al mes?","9.99")||0;'),
        ('`<b>Someone sent you their receipt:</b> they pay about <b>${cur}${Math.round(+v)}/month</b> (${cur}${Math.round(+v*120).toLocaleString("en")} over 10 years). Build yours and send it back.`', '`<b>Alguien te ha enviado su ticket:</b> paga unos <b>${cur}${Math.round(+v)}/mes</b> (${cur}${Math.round(+v*120).toLocaleString("es")} en 10 años). Haz el tuyo y devuélveselo.`'),
        ('g.fillText("SUBSCRIPTION RECEIPT",540,180)', 'g.fillText("TICKET DE SUSCRIPCIONES",540,180)'), ('g.fillText("worth one? · lifetime edition",540,222)', 'g.fillText("worth one? · edición vitalicia",540,222)'),
        ('g.fillText(cur+state.m.toFixed(2)+" a month doesn\'t look like much",540,330)', 'g.fillText(cur+state.m.toFixed(2)+" al mes no parece mucho",540,330)'), ('g.fillText("over 10 years",540,505)', 'g.fillText("en 10 años",540,505)'),
        ('row("+"+(state.items.length-6)+" more","",y)', 'row("+"+(state.items.length-6)+" más","",y)'),
        ('row("Per year",fmt(state.y),y);y+=48;row("20 years",fmt(state.y20),y);y+=48;row("Your tier",state.tier.slice(0,26),y)', 'row("Al año",fmt(state.y),y);y+=48;row("20 años",fmt(state.y20),y);y+=48;row("Tu nivel",state.tier.slice(0,26),y)'),
        ('g.fillText("10 years buys ≈",150,y)', 'g.fillText("10 años compran ≈",150,y)'),
        ('g.fillText("get yours · "+(window.WO_SITE||"").replace("https://","")+"/drops/subscription-receipt/",540,1225)', 'g.fillText("el tuyo · "+(window.WO_SITE||"").replace("https://","")+"/es/drops/subscription-receipt/",540,1225)'),
        ('text:"My subscriptions cost "+fmt(state.y10)+" over 10 years. What is your receipt? (free)"', 'text:"Mis suscripciones cuestan "+fmt(state.y10)+" en 10 años. ¿Cuál es tu ticket? (gratis)"'),
        ('"my-subscription-receipt.png"', '"mi-ticket-suscripciones.png"'),
        ('function fmt(v){return cur+Math.round(v).toLocaleString("en")}', 'function fmt(v){return cur+Math.round(v).toLocaleString("es")}'),
    ],
}


def build():
    for rel, pairs in PAGES.items():
        src = os.path.join(DOCS, rel)
        s = open(src, encoding="utf-8").read()
        missing = []
        for a, b in COMMON + pairs:
            if a in s:
                s = s.replace(a, b)
            elif (a, b) in pairs:
                missing.append(a[:60])
        depth = rel.count("/")
        up = "../" * depth
        en_url = f"{SITE}/{rel.replace('index.html', '')}"
        es_url = f"{SITE}/es/{rel.replace('index.html', '')}"
        s = s.replace(f'<link rel="canonical" href="{en_url}">', f'<link rel="canonical" href="{es_url}">')
        s = s.replace(f'<meta property="og:url" content="{en_url}">', f'<meta property="og:url" content="{es_url}">')
        s = s.replace(f'href="{up}style.css"', f'href="{up}../style.css"').replace(f'src="{up}config.js"', f'src="{up}../config.js"').replace(f'src="{up}app.js"', f'src="{up}../app.js"')
        s = s.replace('<body data-drop=', '<body data-lang="es" data-drop=')
        dst = os.path.join(DOCS, "es", rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        open(dst, "w", encoding="utf-8", newline="\n").write(s)
        print("es/" + rel, "missing:" if missing else "ok", *missing)


if __name__ == "__main__":
    build()
