#!/usr/bin/env python3
"""Builds the Spanish versions of the hand-written pages (docs/es/...) from the English originals by exact
string replacement of visible copy. Run after editing the English pages: python site/i18n_es.py
Adds lang="es", canonical/hreflang, and relinks assets. Generated pages (screen-time, subscriptions, drops
catalogue, embed, notes index) are produced in Spanish by site/build.py.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
SITE = "https://furiadelimon.github.io/worth-one"

COMMON = [
    ('<html lang="en">', '<html lang="es">'),
    ('<a href="drops/">Drops</a><a href="notes/">Lab notes</a><a href="embed/">Embed</a><a href="about.html">About</a>', '<a href="drops/">Drops</a><a href="embed/">Insertar</a><a href="about.html">Acerca de</a><a href="../" hreflang="en">English</a>'),
    ('<a href="../">Drops</a><a href="../../embed/">Embed</a><a href="../../about.html">About</a>', '<a href="../">Drops</a><a href="../../embed/">Insertar</a><a href="../../about.html">Acerca de</a><a href="../../../drops/" hreflang="en">English</a>'),
    ('<a href="drops/">Drops</a><a href="notes/">Lab notes</a><a href="#faq">FAQ</a>', '<a href="drops/">Drops</a><a href="#faq">Preguntas</a><a href="../about.html" hreflang="en">English</a>'),
    ('<a href="drops/">Drops</a><a href="about.html">About</a></span>', '<a href="drops/">Drops</a><a href="about.html">Acerca de</a><a href="../privacy.html" hreflang="en">English</a></span>'),
    ('An independent project by one person. Free things for strangers. One car.', 'Un proyecto independiente de una sola persona. Cosas gratis para desconocidos. Un coche.'),
    ('<a href="about.html">About</a><a href="about.html#faq">FAQ</a><a href="notes/">Lab notes</a><a href="embed/">Embed</a><a href="privacy.html">Privacy</a>', '<a href="about.html">Acerca de</a><a href="about.html#faq">Preguntas</a><a href="embed/">Insertar</a><a href="privacy.html">Privacidad</a>'),
    ('<a href="./">Home</a><a href="drops/">Drops</a><a href="notes/">Lab notes</a><a href="privacy.html">Privacy</a>', '<a href="./">Inicio</a><a href="drops/">Drops</a><a href="privacy.html">Privacidad</a>'),
    ('<a href="../../">Home</a><a href="../">Drops</a><a href="../../embed/">Embed this</a><a href="../../about.html">About</a><a href="../../privacy.html">Privacy</a>', '<a href="../../">Inicio</a><a href="../">Drops</a><a href="../../embed/">Insertar</a><a href="../../about.html">Acerca de</a><a href="../../privacy.html">Privacidad</a>'),
    ('<a href="./">Home</a><a href="drops/">Drops</a><a href="about.html">About</a></footer>', '<a href="./">Inicio</a><a href="drops/">Drops</a><a href="about.html">Acerca de</a></footer>'),
    ('Try another receipt', 'Prueba otro ticket'),
    ('<span class="num">FRIEND</span><span class="tag">games</span><b>Words Before Coffee</b><p>Three words to wake up. Daily word games, no registration, no ads. From the same kitchen (in Spanish).</p>', '<span class="num">AMIGO</span><span class="tag">juegos</span><b>Words Before Coffee</b><p>Tres palabras para despertar. Juegos de palabras diarios, sin registro, sin anuncios. De la misma cocina.</p>'),
    ('<span class="num">PLAY</span><b>Words Before Coffee</b><p>Daily word games, no registration, no ads. In Spanish.</p>', '<span class="num">JUGAR</span><b>Words Before Coffee</b><p>Juegos de palabras diarios, sin registro, sin anuncios.</p>'),
    ('The image is built on your phone. Nothing you type is uploaded.', 'La imagen se genera en tu móvil. Nada de lo que escribes se envía.'),
    ('The image is built on your device. Nothing you type is uploaded.', 'La imagen se genera en tu dispositivo. Nada de lo que escribes se envía.'),
]

PAGES = {
    "index.html": [
        ('<title>Worth One? · Free little things for strangers. Goal: one car.</title>', '<title>Worth One? · Cosas gratis para desconocidos. Objetivo: un coche.</title>'),
        ('content="Free, instant tools that print the number you never see: your scrolling as a receipt, your subscriptions over ten years. No sign-up, no ads. Made by one person to buy a car."', 'content="Herramientas gratis e instantáneas que imprimen el número que nunca ves: tu scroll como un ticket, tus suscripciones a diez años. Sin registro, sin anuncios. Hechas por una persona para comprarse un coche."'),
        ('<span class="eyebrow">Free tools · no sign-up · no ads</span>', '<span class="eyebrow">Herramientas gratis · sin registro · sin anuncios</span>'),
        ('<h1>Small tools that print<br><em>the number you never see.</em></h1>', '<h1>Pequeñas herramientas que imprimen<br><em>el número que nunca ves.</em></h1>'),
        ('<p class="lead">Your scrolling as a receipt. Your subscriptions over ten years. Free, instant, made to be sent to a friend. One person makes them to buy a car, and only asks one thing afterwards: was it worth €1?</p>', '<p class="lead">Tu scroll como un ticket de compra. Tus suscripciones a diez años. Gratis, al instante, hechas para enviárselas a alguien. Una persona las crea para comprarse un coche y solo pregunta una cosa después: ¿valía 1 €?</p>'),
        ('Get your doomscroll receipt →', 'Saca tu ticket de scroll →'), ('Why does this exist?', '¿Por qué existe esto?'),
        ('<p class="muted">Pick one. Takes ten seconds.</p>', '<p class="muted">Elige uno. Diez segundos.</p>'),
        ('<b>Doomscroll Receipt</b><p>How much of your life goes to scrolling? Get the receipt. Screenshot it. Compare with a friend.</p>', '<b>Ticket de Doomscroll</b><p>¿Cuánta vida se te va en hacer scroll? Saca el ticket. Haz captura. Compárala con alguien.</p>'),
        ('<b>Subscription Lifetime Receipt</b><p>What your subscriptions really cost over 10 years, printed on a receipt you won\'t like.</p>', '<b>Ticket de Suscripciones</b><p>Lo que de verdad cuestan tus suscripciones en 10 años, impreso en un ticket que no te va a gustar.</p>'),
        ('<b>Weekends Left</b><p>A grid of the weekends you statistically have left. Poignant, not morbid.</p>', '<b>Fines de semana que te quedan</b><p>Una cuadrícula con los fines de semana que estadísticamente te quedan. Conmovedor, no morboso.</p>'),
        ('<span class="tag soon">next</span>', '<span class="tag soon">próximo</span>'),
        ('<p class="small" style="margin-top:12px"><a href="drops/">All drops and what\'s coming →</a></p>', '<p class="small" style="margin-top:12px"><a href="drops/">Todos los drops y lo que viene →</a></p>'),
        ('<h2>The car fund</h2>\n<p class="small muted">Nothing is charged yet. Each "worth €1" is counted, not billed, until enough people say yes.</p>', '<h2>El fondo del coche</h2>\n<p class="small muted">Todavía no se cobra nada. Cada "vale 1 €" se cuenta, no se cobra, hasta que suficiente gente diga que sí.</p>'),
        ('<b>Real money: <span class="real">€0 / €30,000</span></b>', '<b>Dinero real: <span class="real">€0 / €30,000</span></b>'),
        ('<span>people said "worth €1+"</span>', '<span>personas dijeron "vale 1 €+"</span>'), ('<span>intended value (not money)</span>', '<span>valor declarado (no dinero)</span>'), ('<span>countries reached</span>', '<span>países alcanzados</span>'),
        ('<h2>How it works</h2>\n<p><b>1.</b> Use a tool. Free, no account, nothing to install.</p>\n<p><b>2.</b> If it was worth something, say so: €1, €3, €5, or not.</p>\n<p><b>3.</b> When enough people say yes, optional contributions open. All of it goes to one car, counted publicly above.</p>', '<h2>Cómo funciona</h2>\n<p><b>1.</b> Usa una herramienta. Gratis, sin cuenta, sin instalar nada.</p>\n<p><b>2.</b> Si te ha valido algo, dilo: 1 €, 3 €, 5 €, o no.</p>\n<p><b>3.</b> Cuando suficiente gente diga que sí, se abren las aportaciones opcionales. Todo va a un coche, contado públicamente arriba.</p>'),
        ('data-share="Free tool that prints your scrolling as a receipt. Try it:">Share</a><a class="btn sm ghost" href="about.html">Why a car?</a><a class="btn sm ghost" href="embed/">Embed a tool</a>', 'data-share="Herramienta gratis que imprime tu scroll como un ticket. Pruébala:">Compartir</a><a class="btn sm ghost" href="about.html">¿Por qué un coche?</a><a class="btn sm ghost" href="embed/">Insertar en tu web</a>'),
        ('<a href="https://github.com/Furiadelimon/worth-one">Source</a>', '<a href="https://github.com/Furiadelimon/worth-one">Código</a>'),
    ],
    "about.html": [
        ('<title>About · Worth One? The honest car experiment</title>', '<title>Acerca de · Worth One? El experimento honesto del coche</title>'),
        ('content="What Worth One is, why it exists, where the money goes (one car), and what it is not. Full transparency, FAQ, terms."', 'content="Qué es Worth One, por qué existe, a dónde va el dinero (un coche) y qué no es. Transparencia total, preguntas frecuentes, condiciones."'),
        ('<span class="eyebrow">About</span>\n<h1>What is <em>this?</em></h1>', '<span class="eyebrow">Acerca de</span>\n<h1>¿Qué es <em>esto?</em></h1>'),
        ('<p class="lead">One person wants to buy a car. Instead of asking for money, they make free, useful, slightly absurd little web tools and ask one question after each: <i>was this worth €1 to you?</i></p>', '<p class="lead">Una persona quiere comprarse un coche. En vez de pedir dinero, hace pequeñas herramientas web gratis, útiles y un poco absurdas, y pregunta una sola cosa después de cada una: <i>¿te ha valido 1 €?</i></p>'),
        ('<h2>Why does it exist?</h2>\n<p>Because "free stuff on the internet" usually hides the price: your data, your attention, ads. Here everything is free and stays free, and the price is optional and stated up front. The goal is embarrassingly concrete: one car, €30,000.</p>', '<h2>¿Por qué existe?</h2>\n<p>Porque lo "gratis" en internet suele esconder el precio: tus datos, tu atención, anuncios. Aquí todo es gratis y seguirá siéndolo, y el precio es opcional y se dice de entrada. El objetivo es vergonzosamente concreto: un coche, 30.000 €.</p>'),
        ('<h2>The car fund, exactly</h2>\n<p><b>Target:</b> €30,000. <b>Real money received so far:</b> €0. Payments are not open yet.</p>\n<p>Until they open, the site only records <b>intention</b>: how many people said "worth €1 / €3 / €5" and how many said "not worth it". Intention is shown separately and is never counted as money. When enough people have said yes, a normal payment provider will be connected and real contributions will show on the homepage, publicly.</p>\n<p><b>Where every euro goes:</b> the personal purchase of one car. Not to a company. Not to a cause. Not to "running costs". If the target is reached, the purchase will be documented here.</p>\n<p><b>What it is not:</b> not an investment, not equity, not crowdfunding for a business, not charity, not an emergency, not a promise of any return. A contribution is a voluntary gift, like buying a stranger a coffee because their thing made your day slightly better.</p>',
         '<h2>El fondo del coche, exactamente</h2>\n<p><b>Objetivo:</b> 30.000 €. <b>Dinero real recibido hasta ahora:</b> 0 €. Los pagos todavía no están abiertos.</p>\n<p>Hasta que se abran, la web solo registra <b>intención</b>: cuánta gente dijo "vale 1 / 3 / 5 €" y cuánta dijo "no vale". La intención se muestra aparte y nunca se cuenta como dinero. Cuando suficiente gente haya dicho que sí, se conectará un proveedor de pagos normal y las aportaciones reales se mostrarán en la portada, públicamente.</p>\n<p><b>A dónde va cada euro:</b> a la compra personal de un coche. No a una empresa. No a una causa. No a "gastos de funcionamiento". Si se alcanza el objetivo, la compra se documentará aquí.</p>\n<p><b>Lo que no es:</b> no es una inversión, ni participaciones, ni crowdfunding de una empresa, ni caridad, ni una emergencia, ni promesa de retorno alguno. Una aportación es un regalo voluntario, como invitar a un café a un desconocido porque su cosa te ha mejorado un poco el día.</p>'),
        ('<h2>What can I use?</h2>\n<p>Drops. Small web experiences that work instantly in a browser: calculators, receipts, tests, visualisations, generators, little games. No accounts, no apps, no paywalls. See the <a href="drops/">list</a>. New ones are added continuously; the ones nobody likes are removed. You can also <a href="embed/">put any drop on your own site</a> for free.</p>', '<h2>¿Qué puedo usar?</h2>\n<p>Drops. Pequeñas experiencias web que funcionan al instante en el navegador: calculadoras, tickets, tests, visualizaciones, generadores, juegos. Sin cuentas, sin apps, sin muros de pago. Mira la <a href="drops/">lista</a>. Se añaden nuevos continuamente; los que no gustan a nadie se eliminan. También puedes <a href="embed/">poner cualquier drop en tu propia web</a> gratis.</p>'),
        ('<h2>Why would I share it?</h2>\n<p>Because the results are personal and slightly ridiculous, and that is what people send each other. Sharing is also the only "payment" the project needs right now. Every drop has a share panel that builds an image on your device, plus WhatsApp, Telegram, email and a link that lets a friend compare with you.</p>', '<h2>¿Por qué lo compartiría?</h2>\n<p>Porque los resultados son personales y un poco ridículos, y eso es lo que la gente se envía. Compartir es además el único "pago" que el proyecto necesita ahora. Cada drop tiene un panel para compartir que genera una imagen en tu dispositivo, más WhatsApp, Telegram, email y un enlace para que alguien se compare contigo.</p>'),
        ('<h2>Who is behind it?</h2>\n<p>One person, deliberately not named: the tools should be judged on whether they are worth it, not on who made them. No company, no organisation, no charity. Software does much of the routine work, under simple rules: no spam, no fake accounts, no bought attention, no fake results.</p>', '<h2>¿Quién está detrás?</h2>\n<p>Una persona, que deliberadamente no se nombra: las herramientas deben juzgarse por si valen la pena, no por quién las hizo. Sin empresa, sin organización, sin ONG. El software hace gran parte del trabajo rutinario, con reglas simples: sin spam, sin cuentas falsas, sin atención comprada, sin resultados falsos.</p>'),
        ('<h2>FAQ</h2>', '<h2>Preguntas frecuentes</h2>'),
        ('<details><summary>Is anything charged when I click "Worth €1"?</summary><p>No. Nothing. Right now the button records intention only. Real payments are closed until a human decides to open them, and the homepage will say so clearly when that happens.</p></details>', '<details><summary>¿Se cobra algo al pulsar "Vale 1 €"?</summary><p>No. Nada. Ahora mismo el botón solo registra intención. Los pagos reales están cerrados hasta que una persona decida abrirlos, y la portada lo dirá claramente cuando ocurra.</p></details>'),
        ('<details><summary>Why a car and not something noble?</summary><p>Because it is true. Fake nobility is worse than honest smallness. You are not asked to care about the car; you are asked whether a free tool was worth €1.</p></details>', '<details><summary>¿Por qué un coche y no algo noble?</summary><p>Porque es verdad. La nobleza fingida es peor que la pequeñez honesta. No se te pide que te importe el coche; se te pregunta si una herramienta gratis te valió 1 €.</p></details>'),
        ('<details><summary>Who are you?</summary><p>One person, not named. To reach the project, open an issue on <a href="https://github.com/Furiadelimon/worth-one">GitHub</a>.</p></details>', '<details><summary>¿Quién eres?</summary><p>Una persona, sin nombre. Para contactar con el proyecto, abre un issue en <a href="https://github.com/Furiadelimon/worth-one">GitHub</a>.</p></details>'),
        ('<details><summary>What happens to my data?</summary><p>Very little. An anonymous random id in your browser, the page you viewed, the country your connection comes from, and your answers. No names, no ads, no trackers from third parties. If you leave an email to be told when payments open, it is used for that one message and nothing else. Details in the <a href="privacy.html">privacy page</a>.</p></details>', '<details><summary>¿Qué pasa con mis datos?</summary><p>Muy poco. Un identificador aleatorio anónimo en tu navegador, la página que has visto, el país de tu conexión y tus respuestas. Sin nombres, sin anuncios, sin rastreadores de terceros. Si dejas un email para que te avisen cuando se abran los pagos, se usa para ese único mensaje y nada más. Detalles en la <a href="privacy.html">página de privacidad</a>.</p></details>'),
        ('<details><summary>What if the target is never reached?</summary><p>Then the internet decided the tools were not worth it, and that is a valid result. Everything stays free anyway.</p></details>', '<details><summary>¿Y si nunca se alcanza el objetivo?</summary><p>Entonces internet habrá decidido que las herramientas no valían la pena, y ese es un resultado válido. Todo sigue siendo gratis igualmente.</p></details>'),
        ('<details><summary>Can I suggest a drop, or embed one?</summary><p>Yes and yes. Suggest via <a href="https://github.com/Furiadelimon/worth-one/issues">GitHub issues</a>; embed via the <a href="embed/">embed page</a>.</p></details>', '<details><summary>¿Puedo proponer un drop o insertar uno en mi web?</summary><p>Sí y sí. Propón en <a href="https://github.com/Furiadelimon/worth-one/issues">GitHub</a>; inserta desde la <a href="embed/">página de inserción</a>.</p></details>'),
        ('<details><summary>Terms, briefly</summary><p>The tools are provided as they are, for entertainment and general information, without warranties. Numbers are arithmetic on what you type, not professional advice of any kind. Contributions, when enabled, are voluntary gifts to a private person with no goods, services, rights or returns attached, and are not refundable except where the law requires it.</p></details>', '<details><summary>Condiciones, en breve</summary><p>Las herramientas se ofrecen tal cual, para entretenimiento e información general, sin garantías. Los números son aritmética sobre lo que escribes, no asesoramiento profesional de ningún tipo. Las aportaciones, cuando se habiliten, son regalos voluntarios a una persona privada sin bienes, servicios, derechos ni retornos asociados, y no son reembolsables salvo que la ley lo exija.</p></details>'),
        ('Try the first drop →</a><a class="btn ghost sm" href="#" data-share="Weirdly honest internet experiment: free tools, one car, no tricks.">Share this</a>', 'Prueba el primer drop →</a><a class="btn ghost sm" href="#" data-share="Experimento de internet raramente honesto: herramientas gratis, un coche, sin trucos.">Compartir</a>'),
        ('<a href="https://github.com/Furiadelimon/worth-one">Source</a>', '<a href="https://github.com/Furiadelimon/worth-one">Código</a>'),
    ],
    "privacy.html": [
        ('<title>Privacy · Worth One?</title>', '<title>Privacidad · Worth One?</title>'),
        ('<h1>Privacy</h1><p class="lead">Short, because there is not much to say.</p>', '<h1>Privacidad</h1><p class="lead">Corta, porque no hay mucho que decir.</p>'),
        ('<h3>What is collected</h3>\n<p>A random anonymous id stored in your browser (localStorage), the pages you view here, the country of your connection (derived from the network, not stored as an IP), the referrer or campaign tag that brought you here, and the answers you give (slider values, "worth €1" choices, shares).</p>', '<h3>Qué se recoge</h3>\n<p>Un identificador aleatorio anónimo guardado en tu navegador (localStorage), las páginas que ves aquí, el país de tu conexión (derivado de la red, no se guarda la IP), la referencia o etiqueta de campaña que te trajo, y las respuestas que das (valores de los controles, elecciones de "vale 1 €", compartidos).</p>'),
        ('<h3>What is not collected</h3>\n<p>No name, no account, no IP address stored, no fingerprinting, no third-party analytics, no advertising trackers, no cookies from other companies. Share images are rendered on your device and are not uploaded.</p>', '<h3>Qué no se recoge</h3>\n<p>Ni nombre, ni cuenta, ni dirección IP almacenada, ni huella digital, ni analítica de terceros, ni rastreadores publicitarios, ni cookies de otras empresas. Las imágenes para compartir se generan en tu dispositivo y no se suben.</p>'),
        ('<h3>Email</h3>\n<p>If you type an email to be told when supporting becomes possible, it is stored on a private server in the EU and used for that single purpose. Open an issue on the GitHub repository (or write to the project address once it is published) to have it deleted.</p>', '<h3>Email</h3>\n<p>Si escribes un email para que te avisen cuando sea posible apoyar, se guarda en un servidor privado en la UE y se usa solo para eso. Abre un issue en el repositorio de GitHub (o escribe a la dirección del proyecto) para que se borre.</p>'),
        ('<h3>Where data lives</h3>\n<p>On a private server operated by the project owner (EU). Embedded widgets additionally count views by the embedding site\'s hostname, anonymously. Public pages are served by GitHub Pages, which has its own <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">privacy statement</a>. Events may pass through Cloudflare\'s network in transit.</p>', '<h3>Dónde están los datos</h3>\n<p>En un servidor privado operado por el responsable del proyecto (UE). Los widgets insertados cuentan además las vistas por el dominio de la web que los inserta, de forma anónima. Las páginas públicas las sirve GitHub Pages, que tiene su propia <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">política de privacidad</a>. Los eventos pueden pasar por la red de Cloudflare en tránsito.</p>'),
        ('<h3>Your rights</h3>\n<p>You can clear the anonymous id by clearing your browser storage. EU residents have the usual GDPR rights; contact via the repository. Controller: the individual behind this project, EU.</p>\n<p class="small muted">Last updated: September 2026.</p>', '<h3>Tus derechos</h3>\n<p>Puedes borrar el identificador anónimo vaciando el almacenamiento del navegador. Los residentes en la UE tienen los derechos habituales del RGPD; contacto a través del repositorio. Responsable: la persona detrás de este proyecto, UE.</p>\n<p class="small muted">Última actualización: septiembre de 2026.</p>'),
    ],
    "drops/doomscroll-receipt/index.html": [
        ('<title>Doomscroll Receipt · Screen time calculator: how much of your life goes to scrolling?</title>', '<title>Ticket de Doomscroll · Calculadora de tiempo de pantalla: ¿cuánta vida se te va en el scroll?</title>'),
        ('content="Free screen time calculator. Enter how long you scroll per day and get a receipt: per year, per decade, days of your life, and what a 30-minute cut gives back. No sign-up. Screenshot it, compare with a friend."', 'content="Calculadora gratis de tiempo de pantalla. Di cuánto haces scroll al día y recibe un ticket: al año, por década, días de tu vida y lo que recuperas quitando 30 minutos. Sin registro. Haz captura y compárala."'),
        ('<span class="eyebrow">Drop #001 · free screen time calculator</span>\n<h1>Doomscroll <em>Receipt</em></h1>\n<p class="lead">How long do you scroll per day? Be honest, nobody is watching. Your phone knows: Settings → Screen Time (iPhone) or Digital Wellbeing (Android).</p>', '<span class="eyebrow">Drop #001 · calculadora gratis de tiempo de pantalla</span>\n<h1>Ticket de <em>Doomscroll</em></h1>\n<p class="lead">¿Cuánto tiempo haces scroll al día? Sé sincero, nadie mira. Tu móvil lo sabe: Ajustes → Tiempo de uso (iPhone) o Bienestar digital (Android).</p>'),
        ('<label for="h"><b>Scrolling per day:</b>', '<label for="h"><b>Scroll al día:</b>'),
        ('<h3>YOUR LIFE RECEIPT</h3>', '<h3>TICKET DE TU VIDA</h3>'), ('worth-one · doomscroll receipt · #', 'worth-one · ticket de doomscroll · #'),
        ('<span>Scrolling / day</span>', '<span>Scroll / día</span>'), ('<span>Per week</span>', '<span>A la semana</span>'), ('<span>Per year</span>', '<span>Al año</span>'),
        ('<span>Next 5 years</span>', '<span>Próximos 5 años</span>'), ('<span>Next 10 years</span>', '<span>Próximos 10 años</span>'), ('<span>Next 20 years</span>', '<span>Próximos 20 años</span>'),
        ('<span>10 years of scrolling ≈</span>', '<span>10 años de scroll ≈</span>'), ('<span>Your tier</span>', '<span>Tu nivel</span>'), ('<span>vs world average*</span>', '<span>vs media mundial*</span>'), ('<span>vs other receipts</span>', '<span>vs otros tickets</span>'),
        ('<span>TOTAL, 10 YEARS</span>', '<span>TOTAL, 10 AÑOS</span>'), ('no refunds · but see below', 'sin devoluciones · pero mira abajo'),
        ('<h2>The refund department</h2>\n<p>Recover <b><span id="mLbl">30</span> min/day</b> and the receipt changes.</p>', '<h2>Departamento de devoluciones</h2>\n<p>Recupera <b><span id="mLbl">30</span> min/día</b> y el ticket cambia.</p>'),
        ('<span>time reclaimed / year</span>', '<span>tiempo recuperado / año</span>'), ('<span>over 10 years</span>', '<span>en 10 años</span>'),
        ('That is not a lecture. It\'s arithmetic. Do with it what you want.', 'No es un sermón. Es aritmética. Haz con ella lo que quieras.'),
        ('<b>Subscription Lifetime Receipt</b><p>What Netflix, Spotify and the gym cost over 10 years.</p>', '<b>Ticket de Suscripciones</b><p>Lo que Netflix, Spotify y el gimnasio cuestan en 10 años.</p>'),
        ('<span class="num">READ</span><b>Screen time, by the hour</b><p>1h, 2h, 3h… what each adds up to over a decade.</p>', '<span class="num">LEER</span><b>Tiempo de pantalla, hora a hora</b><p>1h, 2h, 3h… lo que suma cada una en una década.</p>'),
        ('<h2>What this screen time calculator actually does</h2>\n<p>It takes one number, the time you spend scrolling social feeds per day, and multiplies it out: per week, per year (in full 24-hour days), then over the next 5, 10 and 20 years. It then translates the 10-year figure into things people recognise (books, languages, TV series), gives you a tier name and shows how far you are from the world average. The "refund department" runs the same arithmetic on the minutes you decide to take back.</p>', '<h2>Qué hace realmente esta calculadora de tiempo de pantalla</h2>\n<p>Toma un número, el tiempo que pasas haciendo scroll al día, y lo multiplica: a la semana, al año (en días completos de 24 horas) y en los próximos 5, 10 y 20 años. Luego traduce la cifra de 10 años a cosas reconocibles (libros, idiomas, series), te da un nombre de nivel y muestra a qué distancia estás de la media mundial. El "departamento de devoluciones" hace la misma aritmética con los minutos que decidas recuperar.</p>'),
        ('<h3>How to get a real number</h3>\n<p>Open Screen Time (iPhone) or Digital Wellbeing (Android) and look at the weekly total for social and entertainment apps, then divide by seven. Most people underestimate by 30 to 50 percent, which is why the slider starts at 2h30, close to the global average.</p>', '<h3>Cómo conseguir un número real</h3>\n<p>Abre Tiempo de uso (iPhone) o Bienestar digital (Android), mira el total semanal de apps sociales y de entretenimiento y divide entre siete. La mayoría se queda corta entre un 30 y un 50 por ciento, por eso el control empieza en 2h30, cerca de la media mundial.</p>'),
        ('<h3>Why days instead of hours</h3>\n<p>"Two hours a day" sounds like a habit. "Thirty days a year" sounds like a decision. Same number. The receipt exists because the second framing is the one people remember, and the one they send to a friend.</p>', '<h3>Por qué días y no horas</h3>\n<p>"Dos horas al día" suena a hábito. "Treinta días al año" suena a decisión. Es el mismo número. El ticket existe porque la segunda forma es la que la gente recuerda, y la que envía a un amigo.</p>'),
        ('<h3>What it is not</h3>\n<p>It is not a diagnosis, not a health claim and not a judgement. Some scrolling is rest, some is work, some is joy. The receipt only shows the total so that whatever you decide, you decide it with the number in front of you.</p>', '<h3>Lo que no es</h3>\n<p>No es un diagnóstico, ni una afirmación sobre salud, ni un juicio. Parte del scroll es descanso, parte es trabajo, parte es alegría. El ticket solo muestra el total para que, decidas lo que decidas, lo hagas con el número delante.</p>'),
        ('*World average time on social media is roughly 2h20/day (DataReportal, Digital 2025). Everything here is arithmetic on the number you typed, not advice about your health.', '*La media mundial en redes sociales ronda las 2h20/día (DataReportal, Digital 2025). Todo esto es aritmética sobre el número que escribiste, no consejo sobre tu salud.'),
        # JS strings
        ("[1,'Light thumb'],[2,'Casual scroller'],[3,'Regular'],[4,'Committed'],[6,'Heavy rotation'],[99,'Professional thumb athlete']", "[1,'Pulgar ligero'],[2,'Scroll casual'],[3,'Habitual'],[4,'Comprometido'],[6,'Alta rotación'],[99,'Atleta profesional del pulgar']"),
        ("'• reading '+books.toLocaleString('en')+' books (6h each)'", "'• leer '+books.toLocaleString('es')+' libros (6h cada uno)'"),
        ("'• learning '+(Math.floor(lang))+' language'+(lang>=2?'s':'')+' to conversational level'", "'• aprender '+(Math.floor(lang))+' idioma'+(lang>=2?'s':'')+' a nivel conversacional'"),
        ("'• watching every episode of Friends '+(friends<1?'0.'+Math.round(friends*10):Math.round(friends*10)/10)+' times'", "'• ver todos los episodios de Friends '+(friends<1?'0.'+Math.round(friends*10):Math.round(friends*10)/10)+' veces'"),
        ("'• the extended Lord of the Rings trilogy, '+lotr.toLocaleString('en')+' times'", "'• la trilogía extendida del Señor de los Anillos, '+lotr.toLocaleString('es')+' veces'"),
        ("const fmtD=d=>d<1?Math.round(d*24)+' hours':d<60?(Math.round(d*10)/10).toLocaleString('en')+' days':d<365?Math.round(d)+' days':(Math.round(d/365.25*100)/100).toLocaleString('en')+' years';", "const fmtD=d=>d<1?Math.round(d*24)+' horas':d<60?(Math.round(d*10)/10).toLocaleString('es')+' días':d<365?Math.round(d)+' días':(Math.round(d/365.25*100)/100).toLocaleString('es')+' años';"),
        ("$('#r_pct').textContent='more than '+c.pct_below+'% of '+c.n.toLocaleString('en')", "$('#r_pct').textContent='más que el '+c.pct_below+'% de '+c.n.toLocaleString('es')"),
        ("'<b>Someone sent you their receipt:</b> they scroll <b>'+fmtH(fv)+'/day</b> ('+fmtD(fv*365.25/24)+' a year). The slider is set to theirs. Move it to yours, then send it back.'", "'<b>Alguien te ha enviado su ticket:</b> hace scroll <b>'+fmtH(fv)+'/día</b> ('+fmtD(fv*365.25/24)+' al año). El control está en su valor. Ponlo en el tuyo y devuélveselo.'"),
        ("g.fillText('YOUR LIFE RECEIPT',540,190)", "g.fillText('TICKET DE TU VIDA',540,190)"), ("g.fillText('doomscroll receipt · worth one?',540,240)", "g.fillText('ticket de doomscroll · worth one?',540,240)"),
        ("row('Scrolling / day',fmtH(state.x),350);row('Per year',fmtD(state.yearD),410);line(450);row('Next 10 years',fmtD(state.d10),520);row('Next 20 years',fmtD(state.d20),580)", "row('Scroll / día',fmtH(state.x),350);row('Al año',fmtD(state.yearD),410);line(450);row('Próximos 10 años',fmtD(state.d10),520);row('Próximos 20 años',fmtD(state.d20),580)"),
        ("g.fillText('10 years of scrolling ≈',150,680)", "g.fillText('10 años de scroll ≈',150,680)"),
        ("row('Your tier',state.tier,950);row('vs world average',(state.dif>=0?'+':'')+state.dif+'%',1010);line(1050);row('TOTAL, 10 YEARS',fmtD(state.d10),1130,true)", "row('Tu nivel',state.tier,950);row('vs media mundial',(state.dif>=0?'+':'')+state.dif+'%',1010);line(1050);row('TOTAL, 10 AÑOS',fmtD(state.d10),1130,true)"),
        ("g.fillText('get yours: '+(window.WO_SITE||'').replace('https://','')+'/drops/doomscroll-receipt/',540,1220)", "g.fillText('el tuyo: '+(window.WO_SITE||'').replace('https://','')+'/es/drops/doomscroll-receipt/',540,1220)"),
        ("text:'My doomscroll receipt: '+fmtH(state.x)+'/day = '+fmtD(state.d10)+' over 10 years. What is yours? (free)'", "text:'Mi ticket de doomscroll: '+fmtH(state.x)+'/día = '+fmtD(state.d10)+' en 10 años. ¿Cuál es el tuyo? (gratis)'"),
        ("'my-doomscroll-receipt.png'", "'mi-ticket-doomscroll.png'"),
    ],
    "drops/subscription-receipt/index.html": [
        ('<title>Subscription Lifetime Receipt · Subscription cost calculator: what they really cost over 10 years</title>', '<title>Ticket de Suscripciones · Calculadora del coste de tus suscripciones en 10 años</title>'),
        ('content="Free subscription cost calculator. Tap your subscriptions, get a receipt: per month, per year, 10 years, 20 years, and what that money is in real things. No sign-up."', 'content="Calculadora gratis del coste de suscripciones. Marca las tuyas y recibe un ticket: al mes, al año, 10 años, 20 años, y qué es ese dinero en cosas reales. Sin registro."'),
        ('<span class="eyebrow">Drop #002 · free subscription cost calculator</span>\n<h1>Subscription <em>Lifetime</em> Receipt</h1>\n<p class="lead">Tap what you pay for. Fix the prices if yours differ. The receipt prints what it costs over ten and twenty years, and what that money is in real things.</p>', '<span class="eyebrow">Drop #002 · calculadora gratis del coste de suscripciones</span>\n<h1>Ticket de <em>Suscripciones</em></h1>\n<p class="lead">Marca lo que pagas. Corrige los precios si los tuyos son otros. El ticket imprime lo que cuesta en diez y veinte años, y qué es ese dinero en cosas reales.</p>'),
        ('<b>Your subscriptions (per month)</b>', '<b>Tus suscripciones (al mes)</b>'), ('+ add your own', '+ añade la tuya'),
        ('<h3>SUBSCRIPTION RECEIPT</h3>', '<h3>TICKET DE SUSCRIPCIONES</h3>'), ('worth-one · lifetime edition · #', 'worth-one · edición vitalicia · #'),
        ('<span>Per month</span>', '<span>Al mes</span>'), ('<span>Per year</span>', '<span>Al año</span>'), ('<span>5 years</span>', '<span>5 años</span>'), ('<span>10 years</span>', '<span>10 años</span>'), ('<span>20 years</span>', '<span>20 años</span>'),
        ('<span>10 years buys ≈</span>', '<span>10 años compran ≈</span>'), ('<span>Your tier</span>', '<span>Tu nivel</span>'), ('<span>vs other receipts</span>', '<span>vs otros tickets</span>'), ('<span>TOTAL, 10 YEARS</span>', '<span>TOTAL, 10 AÑOS</span>'),
        ('auto-renews · like everything else', 'se renueva solo · como todo lo demás'),
        ('<h2>The cancel department</h2>\n<p>Untick one thing above and watch the 10-year line. That\'s the whole trick. No advice, just the number you were never shown.</p>\n<p class="small muted">Prices are typical 2026 list prices and only defaults; edit them. No inflation, no investing, no "if you had bought Bitcoin". Just what you pay.</p>', '<h2>Departamento de bajas</h2>\n<p>Desmarca una cosa arriba y mira la línea de 10 años. Ese es todo el truco. Sin consejos, solo el número que nunca te enseñaron.</p>\n<p class="small muted">Los precios son los de lista típicos de 2026 y solo valores por defecto; edítalos. Sin inflación, sin inversiones, sin "si hubieras comprado Bitcoin". Solo lo que pagas.</p>'),
        ('<b>Doomscroll Receipt</b><p>How much of your life goes to scrolling, in days.</p>', '<b>Ticket de Doomscroll</b><p>Cuánta vida se te va en el scroll, en días.</p>'),
        ('<span class="num">READ</span><b>Subscriptions, one by one</b><p>What Netflix, Spotify or the gym alone cost over a decade.</p>', '<span class="num">LEER</span><b>Suscripciones, una a una</b><p>Lo que Netflix, Spotify o el gimnasio cuestan solos en una década.</p>'),
        ('<h2>What this subscription cost calculator does</h2>\n<p>You tap the subscriptions you pay for, correct the prices, and it prints the monthly and yearly total, then the 5, 10 and 20-year cost. The 10-year line is converted into things people can picture: a share of a car, coffees, weeks of groceries, flights. There is no inflation adjustment and no investment fantasy; it is only what leaves your account at today\'s prices.</p>', '<h2>Qué hace esta calculadora de suscripciones</h2>\n<p>Marcas las suscripciones que pagas, corriges los precios, e imprime el total mensual y anual, y después el coste a 5, 10 y 20 años. La línea de 10 años se convierte en cosas que se pueden imaginar: parte de un coche, cafés, semanas de compra, vuelos. Sin ajuste por inflación ni fantasías de inversión; solo lo que sale de tu cuenta a precios de hoy.</p>'),
        ('<h3>Why the 10-year line matters</h3>\n<p>Subscriptions are priced to feel small per month. Nobody signs up for "€1,680 of streaming per decade", but that is what €14 a month is. Seeing the decade total next to the monthly price is usually enough to cancel one thing, which is the entire purpose of this page.</p>', '<h3>Por qué importa la línea de 10 años</h3>\n<p>Las suscripciones están pensadas para parecer pequeñas al mes. Nadie se apunta a "1.680 € de streaming por década", pero eso son 14 € al mes. Ver el total de la década junto al precio mensual suele bastar para dar de baja una cosa, que es el único propósito de esta página.</p>'),
        ('<h3>How to use it honestly</h3>\n<p>Include the ones you forget: cloud storage, an app you no longer open, the second streaming service, the phone insurance. Then remove one and watch the receipt reprint. Repeat until the number stops bothering you.</p>', '<h3>Cómo usarla con honestidad</h3>\n<p>Incluye las que olvidas: el almacenamiento en la nube, una app que ya no abres, el segundo servicio de streaming, el seguro del móvil. Luego quita una y mira cómo se reimprime el ticket. Repite hasta que el número deje de molestarte.</p>'),
        ('["Gym",35,1]', '["Gimnasio",35,1]'), ('["Dating app",20,0]', '["App de citas",20,0]'), ('["News / magazine",10,0]', '["Prensa / revista",10,0]'), ('["Meal kit",60,0]', '["Comida a domicilio",60,0]'), ('["Adobe / software",25,0]', '["Adobe / software",25,0]'), ('["Phone plan",20,0]', '["Tarifa móvil",20,0]'), ('["ChatGPT / AI",20,0]', '["ChatGPT / IA",20,0]'),
        ('const tiers=[[25,"Minimalist"],[60,"Streaming citizen"],[120,"Bundle enjoyer"],[200,"Recurring revenue hero"],[1e9,"The landlord\'s favourite tenant"]];', 'const tiers=[[25,"Minimalista"],[60,"Ciudadano del streaming"],[120,"Amante del pack"],[200,"Héroe del ingreso recurrente"],[1e9,"El inquilino favorito del casero"]];'),
        ('\'<div class="c">nothing selected</div>\'', '\'<div class="c">nada seleccionado</div>\''),
        ('const eq=[`• ${(y10/30000*100).toFixed(0)}% of the car this site wants (${cur}30,000)`,`• ${Math.round(y10/3).toLocaleString("en")} coffees at ${cur}3`,`• ${Math.round(y10/80).toLocaleString("en")} weeks of groceries at ${cur}80`,`• ${(y10/1200).toFixed(1)} return flights at ${cur}1,200`];', 'const eq=[`• ${(y10/30000*100).toFixed(0)}% del coche que quiere esta web (${cur}30.000)`,`• ${Math.round(y10/3).toLocaleString("es")} cafés a ${cur}3`,`• ${Math.round(y10/80).toLocaleString("es")} semanas de compra a ${cur}80`,`• ${(y10/1200).toFixed(1)} vuelos ida y vuelta a ${cur}1.200`];'),
        ('$(\'#r_pct\').textContent=\'more than \'+c.pct_below+\'% of \'+c.n.toLocaleString(\'en\')', '$(\'#r_pct\').textContent=\'más que el \'+c.pct_below+\'% de \'+c.n.toLocaleString(\'es\')'),
        ('const n=prompt("Name of the subscription?");if(!n)return;const p=+prompt("Price per month?","9.99")||0;', 'const n=prompt("¿Nombre de la suscripción?");if(!n)return;const p=+prompt("¿Precio al mes?","9.99")||0;'),
        ('`<b>Someone sent you their receipt:</b> they pay about <b>${cur}${Math.round(+v)}/month</b> (${cur}${Math.round(+v*120).toLocaleString("en")} over 10 years). Build yours and send it back.`', '`<b>Alguien te ha enviado su ticket:</b> paga unos <b>${cur}${Math.round(+v)}/mes</b> (${cur}${Math.round(+v*120).toLocaleString("es")} en 10 años). Haz el tuyo y devuélveselo.`'),
        ('g.fillText("SUBSCRIPTION RECEIPT",540,190)', 'g.fillText("TICKET DE SUSCRIPCIONES",540,190)'), ('g.fillText("lifetime edition · worth one?",540,240)', 'g.fillText("edición vitalicia · worth one?",540,240)'),
        ('row("+"+(state.items.length-7)+" more","",y)', 'row("+"+(state.items.length-7)+" más","",y)'),
        ('row("Per year",fmt(state.y),y);y+=52;row("10 years",fmt(state.y10),y);y+=52;row("20 years",fmt(state.y20),y)', 'row("Al año",fmt(state.y),y);y+=52;row("10 años",fmt(state.y10),y);y+=52;row("20 años",fmt(state.y20),y)'),
        ('g.fillText("10 years buys ≈",150,y)', 'g.fillText("10 años compran ≈",150,y)'),
        ('row("Your tier",state.tier.slice(0,26),y);y+=64;row("TOTAL, 10 YEARS",fmt(state.y10),y,true)', 'row("Tu nivel",state.tier.slice(0,26),y);y+=64;row("TOTAL, 10 AÑOS",fmt(state.y10),y,true)'),
        ('g.fillText("get yours: "+(window.WO_SITE||"").replace("https://","")+"/drops/subscription-receipt/",540,1220)', 'g.fillText("el tuyo: "+(window.WO_SITE||"").replace("https://","")+"/es/drops/subscription-receipt/",540,1220)'),
        ('text:"My subscriptions cost "+fmt(state.y10)+" over 10 years. What is your receipt? (free)"', 'text:"Mis suscripciones cuestan "+fmt(state.y10)+" en 10 años. ¿Cuál es tu ticket? (gratis)"'),
        ('"my-subscription-receipt.png"', '"mi-ticket-suscripciones.png"'),
        ('function fmt(v){return cur+Math.round(v).toLocaleString("en")}', 'function fmt(v){return cur+Math.round(v).toLocaleString("es")}'),
    ],
}


def build():
    for rel, pairs in PAGES.items():
        src = os.path.join(DOCS, rel)
        s = open(src, encoding="utf-8").read()
        missing = []
        for a, b in COMMON + pairs:
            if a in s:
                s = s.replace(a, b)
            elif (a, b) in pairs:
                missing.append(a[:60])
        depth = rel.count("/")
        up = "../" * depth
        # canonical + hreflang + asset paths
        en_url = f"{SITE}/{rel.replace('index.html', '')}"
        es_url = f"{SITE}/es/{rel.replace('index.html', '')}"
        s = s.replace(f'<link rel="canonical" href="{en_url}">', f'<link rel="canonical" href="{es_url}"><link rel="alternate" hreflang="en" href="{en_url}"><link rel="alternate" hreflang="es" href="{es_url}"><link rel="alternate" hreflang="x-default" href="{en_url}">')
        s = s.replace(f'<meta property="og:url" content="{en_url}">', f'<meta property="og:url" content="{es_url}">')
        s = s.replace(f'href="{up}style.css"', f'href="{up}../style.css"').replace(f'src="{up}config.js"', f'src="{up}../config.js"').replace(f'src="{up}app.js"', f'src="{up}../app.js"')
        s = s.replace('<body data-drop=', '<body data-lang="es" data-drop=')
        dst = os.path.join(DOCS, "es", rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        open(dst, "w", encoding="utf-8", newline="\n").write(s)
        print("es/" + rel, "missing:" if missing else "ok", *missing)
    # English pages get the hreflang alternates too
    for rel in PAGES:
        src = os.path.join(DOCS, rel)
        s = open(src, encoding="utf-8").read()
        en_url = f"{SITE}/{rel.replace('index.html', '')}"
        es_url = f"{SITE}/es/{rel.replace('index.html', '')}"
        tag = f'<link rel="alternate" hreflang="es" href="{es_url}">'
        if tag not in s:
            s = s.replace(f'<link rel="canonical" href="{en_url}">', f'<link rel="canonical" href="{en_url}"><link rel="alternate" hreflang="en" href="{en_url}">{tag}<link rel="alternate" hreflang="x-default" href="{en_url}">')
            open(src, "w", encoding="utf-8", newline="\n").write(s)


if __name__ == "__main__":
    build()
